export type ToolsConfig = typeof toolsConfig;

export const toolsConfig = [
  {
    title: "Design",
    rows: [
      {
        title: "Photopea",
        href: "https://www.photopea.com/",
        icon: "/images/photopea.webp",
        desc: "Advanced image editor",
      },
      {
        title: "Vecta",
        href: "https://vecta.io/nano",
        icon: "/images/vecta.webp",
        desc: "World's Best SVG Compressor",
      },
      {
        title: "Convertio",
        href: "https://convertio.co",
        icon: "/images/convertio.webp",
        desc: "Convert anything to anything",
      },
      {
        title: "Haikei",
        href: "https://haikei.app/",
        icon: "/images/haikei.webp",
        desc: "Generate unique SVG design assets",
      },
      {
        title: "Base64 Image",
        href: "https://www.base64-image.de/",
        icon: "/images/base64.webp",
        desc: "Convert your images to Base64",
      },
      {
        title: "Canva",
        href: "https://www.canva.com/",
        icon: "/images/canva.webp",
        desc: "Design anything",
      },
      {
        title: "Trangram",
        href: "https://www.trangram.com/",
        icon: "/images/trangram.webp",
        desc: "Create motion graphics on one platform",
      },
      {
        title: "Radix Colors",
        href: "https://www.radix-ui.com/colors",
        icon: "/images/radix.webp",
        iconDark: "/images/radix-dark.webp",
        desc: "A gorgeous, accessible color system for user interfaces",
      },
      {
        title: "Tailwindcss Color",
        href: "https://tailwindcss.com/docs/customizing-colors",
        icon: "/images/tailwindcss.webp",
        desc: "Customizing colors",
      },
    ],
  },
  {
    title: "Icon",
    rows: [
      {
        title: "Radix icons",
        href: "https://www.radix-ui.com/icons",
        icon: "/images/radix.webp",
        iconDark: "/images/radix-dark.webp",
        desc: "A crisp set of 15x15 icons",
      },
      {
        title: "Lucide",
        href: "https://lucide.dev/",
        icon: "/images/lucide.webp",
        desc: "Simply beautiful open-source icons",
      },
      {
        title: "Material Icons",
        href: "https://fonts.google.com/icons",
        icon: "/images/material-icons.webp",
        desc: "Google's Material Icons",
      },
      {
        title: "Font Awesome",
        href: "https://fontawesome.com/search",
        icon: "/images/font-awesome.webp",
        desc: "The web's most popular icon set and toolkit",
      },
      {
        title: "Pictogrammers",
        href: "https://pictogrammers.com/libraries/",
        icon: "/images/pictogrammers.webp",
        desc: "A library of free icons for your projects",
      },
      {
        title: "Icones 8",
        href: "https://icones8.fr/icons/color",
        icon: "/images/icones8.webp",
        desc: "Free icons in various styles",
      },
      {
        title: "SVGPORN",
        href: "https://svgporn.com/",
        icon: "/images/svgporn.webp",
        desc: "The best SVGs on the web",
      },
      {
        title: "Clearbit",
        href: "https://clearbit.com/logo",
        icon: "/images/clearbit.webp",
        desc: "Logo API",
      },
      {
        title: "Emojipedia",
        href: "https://emojipedia.org/",
        icon: "/images/emojipedia.webp",
        desc: "Emoji search and copy platform",
      },
    ],
  },
  {
    title: "Library",
    rows: [
      {
        title: "shadcn UI",
        href: "https://ui.shadcn.com/",
        icon: "/images/shadcn-ui.webp",
        desc: "Ract component library",
      },
      {
        title: "Aceternity UI",
        href: "https://ui.aceternity.com/",
        icon: "/images/aceternity-ui.webp",
        desc: "React component library",
      },
      {
        title: "Tailwindcss",
        href: "https://tailwindcss.com/",
        icon: "/images/tailwindcss.webp",
        desc: "A utility-first CSS framework for rapid UI development",
      },
      {
        title: "Bootstrap",
        href: "https://getbootstrap.com/",
        icon: "/images/bootstrap.webp",
        desc: "The world’s most popular front-end open source toolkit",
      },
      {
        title: "Tabler",
        href: "https://tabler.io/",
        icon: "/images/tabler.webp",
        desc: "Open-source dashboard template",
      },
      {
        title: "VueUse",
        href: "https://vueuse.org/",
        icon: "/images/vueuse.webp",
        desc: "Collection of Vue Composition Utilities",
      },
      {
        title: "VuePress",
        href: "https://vuepress.vuejs.org/",
        icon: "/images/vuepress.webp",
        desc: "Vue-powered Static Site Generator",
      },
      {
        title: "Vuetify",
        href: "https://vuetifyjs.com/en/",
        icon: "/images/vuetify.webp",
        desc: "Vue Component Framework",
      },
    ],
  },
  {
    title: "AI",
    rows: [
      {
        title: "ChatGPT",
        href: "https://chat.openai.com/",
        icon: "/images/chatgpt.webp",
        desc: "OpenAI's Chatbot",
      },
      {
        title: "Bing Copilot",
        href: "https://www.bing.com/chat",
        icon: "/images/bing-copilot.webp",
        desc: "Microsoft's Chatbot",
      },
      {
        title: "Gemini",
        href: "https://gemini.google.com/",
        icon: "/images/gemini.webp",
        desc: "Google's Chatbot",
      },
      {
        title: "Perplexity",
        href: "https://www.perplexity.ai/",
        icon: "/images/perplexity.webp",
        desc: "Alternative chatbot",
      },
      {
        title: "Mistral",
        href: "https://mistral.ai/",
        icon: "/images/mistral.webp",
        desc: "Alternative chatbot",
      },
      {
        title: "Claude",
        href: "https://claude.ai/",
        icon: "/images/claude.webp",
        desc: "Alternative chatbot",
      },
      {
        title: "Groq",
        href: "https://groq.com/",
        icon: "/images/groq.webp",
        desc: "Alternative chatbot",
      },
      {
        title: "DALL·E 2",
        href: "https://openai.com/dall-e-2",
        icon: "/images/dalle2.webp",
        desc: "OpenAI's Image Generation",
      },
      {
        title: "Github Copilot",
        href: "https://copilot.github.com/",
        icon: "/images/github-copilot.webp",
        iconDark: "/images/github-copilot-dark.webp",
        desc: "Coding assistant",
      },
      {
        title: "Tabnine",
        href: "https://www.tabnine.com/",
        icon: "/images/tabnine.webp",
        desc: "Coding assistant",
      },
      {
        title: "V0",
        href: "https://v0.dev/",
        icon: "/images/v0.webp",
        iconDark: "/images/v0-dark.webp",
        desc: "Generate UI with shadcn/ui",
      },
      {
        title: "Upscale",
        href: "https://www.upscale.media/",
        icon: "/images/upscale.webp",
        desc: "Image Upscaling and Enhancement",
      },
      {
        title: "Remove bg",
        href: "https://www.remove.bg/",
        icon: "/images/remove-bg.webp",
        desc: "Remove Image Background",
      },
      {
        title: "Watermark Remover",
        href: "https://www.watermarkremover.io/",
        icon: "/images/watermark-remover.webp",
        desc: "Remove watermarks",
      },
      {
        title: "Vectorizer",
        href: "https://vectorizer.ai/",
        icon: "/images/vectorizer.webp",
        desc: "Trace pixels to vectors",
      },
      {
        title: "DeepAI",
        href: "https://deepai.org/",
        icon: "/images/deepai.webp",
        desc: "AI tools and resources",
      },
      {
        title: "Ideogram",
        href: "https://ideogram.ai/",
        icon: "/images/ideogram.webp",
        desc: "Image generator",
      },
      {
        title: "Leonardo",
        href: "https://leonardo.ai/",
        icon: "/images/leonardo.webp",
        desc: "Image generator",
      },
      {
        title: "Seaart",
        href: "https://www.seaart.ai/",
        icon: "/images/seaart.webp",
        desc: "Image generator",
      },
      {
        title: "Midjourney",
        href: "https://www.midjourney.com/",
        icon: "/images/midjourney.webp",
        iconDark: "/images/midjourney-dark.webp",
        desc: "Image generator",
      },
      {
        title: "Clipdrop",
        href: "https://clipdrop.co/",
        icon: "/images/clipdrop.webp",
        iconDark: "/images/clipdrop-dark.webp",
        desc: "Image generator and editor",
      },
      {
        title: "Remaker",
        href: "https://remaker.ai/",
        icon: "/images/remaker.webp",
        desc: "AI face swap",
      },
      {
        title: "Suno AI",
        href: "https://www.suno.ai/",
        icon: "/images/suno-ai.webp",
        desc: "Make a song",
      },
      {
        title: "Udio",
        href: "https://www.udio.com/",
        icon: "/images/udio.webp",
        desc: "Make your music",
      },
      {
        title: "Audiobox",
        href: "https://audiobox.metademolab.com/",
        icon: "/images/audiobox.webp",
        desc: "Sound and voice generator",
      },
      {
        title: "Elevenlabs",
        href: "https://elevenlabs.io/",
        icon: "/images/elevenlabs.webp",
        desc: "Generative voice AI",
      },
      {
        title: "Heygen",
        href: "https://www.heygen.com/",
        icon: "/images/heygen.webp",
        desc: "Video & generative voice",
      },
      {
        title: "Pika",
        href: "https://pika.art/",
        icon: "/images/pika.webp",
        desc: "Video on command",
      },
      {
        title: "Capcut",
        href: "https://www.capcut.com/",
        icon: "/images/capcut.webp",
        desc: "Video editing",
      },
      {
        title: "Submagic",
        href: "https://www.submagic.co/",
        icon: "/images/submagic.webp",
        desc: "Subtitle editor",
      },
      {
        title: "Interior AI",
        href: "https://interiorai.com/",
        icon: "/images/interiorai.webp",
        desc: "AI-generated interior design",
      },
      {
        title: "Room GPT",
        href: "https://www.roomgpt.io/",
        icon: "/images/roomgpt.webp",
        desc: "AI-generated room design",
      },
      {
        title: "Mylens",
        href: "https://mylens.ai/",
        icon: "/images/mylens.webp",
        desc: "Timeline, mindmap generator",
      },
      {
        title: "Pinokio",
        href: "https://pinokio.computer/",
        icon: "/images/pinokio.webp",
        desc: "Install, run, and programmatically control ANY application",
      },
      {
        title: "Ollama",
        href: "https://ollama.com/",
        icon: "/images/ollama.webp",
        desc: "Run Llama 3, Phi 3, Mistral, Gemma, and other models",
      },
      {
        title: "Deepl",
        href: "https://www.deepl.com/translator",
        icon: "/images/deepl.webp",
        desc: "Translator",
      },
    ],
  },
  {
    title: "API",
    rows: [
      {
        title: "Jsonplaceholder",
        href: "https://jsonplaceholder.typicode.com/",
        icon: "/images/jsonplaceholder.webp",
        iconDark: "/images/jsonplaceholder-dark.webp",
        desc: "Fake Online REST API for Testing and Prototyping",
      },
      {
        title: "Unsplash",
        href: "https://unsplash.com/developers",
        icon: "/images/unsplash.webp",
        iconDark: "/images/unsplash-dark.webp",
        desc: "The internet’s source of freely-usable images",
      },
      {
        title: "Ipinfo",
        href: "https://ipinfo.io/",
        icon: "/images/ipinfo.webp",
        desc: "IP address and geolocation data API",
      },
      {
        title: "Ipify API",
        href: "https://www.ipify.org/",
        icon: "/images/ipify.webp",
        desc: "A Simple Public IP Address API",
      },
      {
        title: "Openweathermap",
        href: "https://openweathermap.org/",
        icon: "/images/openweathermap.webp",
        desc: "Weather data API",
      },
      {
        title: "Ntfy",
        href: "https://ntfy.sh/",
        icon: "/images/ntfy.webp",
        desc: "Push notifications made easy",
      },
    ],
  },
  {
    title: "Utility",
    rows: [
      {
        title: "Alternativeto",
        href: "https://alternativeto.net/",
        icon: "/images/alternativeto.webp",
        desc: "Find alternatives to software",
      },
      {
        title: "Useful Forks",
        href: "https://useful-forks.github.io/",
        icon: "/images/useful-forks.webp",
        desc: "Find useful forks of GitHub repositories",
      },
      {
        title: "Readmi",
        href: "https://readmi.xyz/",
        icon: "/images/readmi.webp",
        iconDark: "/images/readmi-dark.webp",
        desc: "Create a beautiful README",
      },
      {
        title: "Json Crack",
        href: "https://jsoncrack.com/",
        icon: "/images/jsoncrack.webp",
        desc: "Understand your JSON better by visualizing",
      },
      {
        title: "Excalidraw",
        href: "https://excalidraw.com/",
        icon: "/images/excalidraw.webp",
        desc: "Virtual whiteboard for sketching hand-drawn like diagrams",
      },
      {
        title: "DBdiagram",
        href: "https://dbdiagram.io/home",
        icon: "/images/dbdiagram.webp",
        desc: "Database diagram tool",
      },
      {
        title: "Regex101",
        href: "https://regex101.com/",
        icon: "/images/regex101.webp",
        desc: "Online regex tester and debugger",
      },
      {
        title: "Virus Total",
        href: "https://www.virustotal.com/gui/home/upload",
        icon: "/images/virustotal.webp",
        desc: "Analyze suspicious files and URLs to detect types of malware",
      },
      {
        title: "List of files by Microsoft",
        href: "https://files.rg-adguard.net/category",
        icon: "/images/ListoffilesbyMicrosoft.webp",
        desc: "Download Windows ISOs",
      },
    ],
  },
  {
    title: "Game",
    rows: [
      {
        title: "Flexbox Froggy",
        href: "https://flexboxfroggy.com",
        icon: "/images/flexboxfroggy.webp",
        desc: "A game for learning CSS flexbox",
      },
      {
        title: "Grid Garden",
        href: "https://cssgridgarden.com/",
        icon: "/images/gridgarden.webp",
        desc: "A game for learning CSS grid",
      },
      {
        title: "Flexbox Defense",
        href: "http://www.flexboxdefense.com/",
        icon: "/images/flexboxdefense.webp",
        iconDark: "/images/flexboxdefense-dark.webp",
        desc: "A game for learning CSS flexbox",
      },
      {
        title: "CSS Diner",
        href: "https://flukeout.github.io/",
        icon: "/images/cssdiner.webp",
        desc: "A game for learning CSS selectors",
      },
    ],
  },
];
